on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: JRMurr/direnv-nix-action@v4.1.0
        with:
          cache-store: "false"
      - name: Test
        shell: bash
        run: |
          ./run_tests.sh
